/*******************************************************************************
 * This file was generated by UI Builder.
 * User should hand edit this file.
 ********************************************************************************/

#include "app_main.h"
#include "uib_views.h"
#include "uib_views_inc.h"

wifi_manager_h wifi;

typedef struct _uib_mainView_control_context {
/* add your variables here */

} uib_mainView_control_context;

void mainView_onuib_view_create(uib_mainView_view_context *vc, Evas_Object *obj,
		void *event_info) {
	wifiCheck(vc);
	wifi = turnOnWifi(vc);
}

void mainView_sendButton_onclicked(uib_mainView_view_context *vc,
		Evas_Object *obj, void *event_info) {
	sendBTN(vc);
}

void mainView_exitButton_onclicked(uib_mainView_view_context *vc,
		Evas_Object *obj, void *event_info) {
	appTERMINATE(vc);
}

Eina_Bool myend_timer_cb(void *data) {
	dlog_print(DLOG_DEBUG, LOG_TAG, "wifiApp closed successfully");
	uib_views_get_instance()->destroy_window_obj();
	ui_app_exit();
	return ECORE_CALLBACK_CANCEL;
}

static void __wifi_manager_deactivated_cb(wifi_error_e result, void *user_data) {
	if (result == WIFI_ERROR_NONE)
		dlog_print(DLOG_INFO, LOG_TAG, "Success to deactivate Wi-Fi device!");
}

void appTERMINATE(void *data) {
	hideBTN(data, 0);
	hideBTN(data, 1);
	showMSG(data, "Turn off WIFI");
	ecore_timer_add(3, myend_timer_cb, data);
	wifi_manager_deactivate(wifi, __wifi_manager_deactivated_cb, data);
	wifi_manager_deinitialize(wifi);
}

void showBTN(void *data, int x) {
	uib_mainView_view_context *vc = data;
	switch (x) {
	case 0:
		evas_object_show(vc->sendButton);
		break;
	case 1:
		evas_object_show(vc->exitButton);
		break;

	default:
		return;
	}
}

void hideBTN(void *data, int x) {
	uib_mainView_view_context *vc = data;
	switch (x) {
	case 0:
		evas_object_hide(vc->sendButton);
		break;
	case 1:
		evas_object_hide(vc->exitButton);
		break;

	default:
		return;
	}
}

void showMSG(void* data, char *msg) {
	uib_mainView_view_context *vc = data;
	elm_object_text_set(vc->msgLabel, msg);
}

