
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/
		#include "g_inc_uib.h"
#include "uib_views.h"
#include "uib_views_inc.h"
#include "uib_app_manager.h"


/* event handler declarations */
void view1_Ok_onclicked(uib_view1_view_context*, Evas_Object*, void*);
void view1_one_onclicked(uib_view1_view_context*, Evas_Object*, void*);
void view1_three_onclicked(uib_view1_view_context*, Evas_Object*, void*);
void view1_two_onclicked(uib_view1_view_context*, Evas_Object*, void*);
void view1_four_onclicked(uib_view1_view_context*, Evas_Object*, void*);
void view1_five_onclicked(uib_view1_view_context*, Evas_Object*, void*);
void view1_reconfig_onclicked(uib_view1_view_context*, Evas_Object*, void*);
void view1_Exit_onclicked(uib_view1_view_context*, Evas_Object*, void*);

uib_view_context* uib_view_view1_create(Evas_Object* parent, void* create_callback_param) {
	uib_view1_view_context* vc = calloc(1, sizeof(uib_view1_view_context));
	vc->parent = parent;
	vc->view_name = "view1";
	vc->indicator_state = ELM_WIN_INDICATOR_SHOW;
	vc->is_user_view = false;
	uib_app_manager_get_instance()->add_view_context((uib_view_context*)vc);
	if (!vc->grid1) {
		vc->grid1= elm_grid_add(parent);
		vc->root_container = vc->grid1;
	}
	uib_views_get_instance()->set_targeted_view((uib_view_context*)vc);

	//bind event handler
	evas_object_smart_callback_add(vc->Ok, "clicked", (Evas_Smart_Cb)view1_Ok_onclicked, vc);
	evas_object_smart_callback_add(vc->one, "clicked", (Evas_Smart_Cb)view1_one_onclicked, vc);
	evas_object_smart_callback_add(vc->three, "clicked", (Evas_Smart_Cb)view1_three_onclicked, vc);
	evas_object_smart_callback_add(vc->two, "clicked", (Evas_Smart_Cb)view1_two_onclicked, vc);
	evas_object_smart_callback_add(vc->four, "clicked", (Evas_Smart_Cb)view1_four_onclicked, vc);
	evas_object_smart_callback_add(vc->five, "clicked", (Evas_Smart_Cb)view1_five_onclicked, vc);
	evas_object_smart_callback_add(vc->reconfig, "clicked", (Evas_Smart_Cb)view1_reconfig_onclicked, vc);
	evas_object_smart_callback_add(vc->Exit, "clicked", (Evas_Smart_Cb)view1_Exit_onclicked, vc);


	evas_object_data_set(vc->root_container, KEY_VIEW_CONTEXT, vc);
	uib_views_create_callback(vc, evas_object_evas_get(vc->root_container), vc->root_container, create_callback_param);
	evas_object_event_callback_add(vc->root_container, EVAS_CALLBACK_DEL, (Evas_Object_Event_Cb)uib_views_destroy_callback, vc);

	return (uib_view_context*)vc;
}
void uib_view1_config_CIRCLE_360x360_portrait() {
	uib_app_manager_st* uib_app_manager = uib_app_manager_get_instance();
	uib_view1_view_context* vc = (uib_view1_view_context*)uib_app_manager->find_view_context("view1");
	if(!vc) {
		return;
	}
	if(vc->grid1) {
		elm_grid_clear(vc->grid1, EINA_FALSE);
		evas_object_size_hint_align_set(vc->grid1, -1.0, -1.0);		evas_object_size_hint_weight_set(vc->grid1, 1.0, 1.0);		elm_grid_size_set(vc->grid1, 1000, 1000);
		if (!vc->bg2) {
			vc->bg2 = elm_bg_add(vc->grid1);
		}
		if(vc->bg2) {
			evas_object_size_hint_align_set(vc->bg2, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->bg2, 1.0, 1.0);			elm_bg_option_set(vc->bg2, (Elm_Bg_Option)ELM_BG_OPTION_SCALE);
			int hexValue = strtol("#0f42db"+1, NULL, 16);
			int r = (hexValue&0xFF0000)>>16;
			int g = (hexValue&0xFF00)>>8;
			int b = (hexValue&0xFF);
			elm_bg_color_set(vc->bg2, r, g, b);
			evas_object_show(vc->bg2);
		}
		if (!vc->Ok) {
			vc->Ok = elm_button_add(vc->grid1);
		}
		if (vc->Ok) {
			evas_object_size_hint_align_set(vc->Ok, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->Ok, 1.0, 1.0);			elm_object_text_set(vc->Ok,_UIB_LOCALE("OK"));
			elm_object_style_set(vc->Ok,"bottom");
			evas_object_show(vc->Ok);
		}
		if (!vc->password) {
			vc->password= elm_entry_add(vc->grid1);
		}
		if(vc->password) {
			elm_object_text_set(vc->password,_UIB_LOCALE("Enter Password"));
			elm_entry_single_line_set(vc->password, EINA_TRUE);
			elm_entry_password_set(vc->password, EINA_FALSE);
			elm_entry_editable_set(vc->password, EINA_FALSE);
			elm_entry_scrollable_set(vc->password, EINA_FALSE);
			evas_object_size_hint_align_set(vc->password, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->password, 1.0, 1.0);
			elm_object_disabled_set(vc->password, EINA_FALSE);
			evas_object_show(vc->password);
		}
		if (!vc->one) {
			vc->one = elm_button_add(vc->grid1);
		}
		if (vc->one) {
			evas_object_size_hint_align_set(vc->one, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->one, 1.0, 1.0);			elm_object_text_set(vc->one,_UIB_LOCALE("1"));
			elm_object_style_set(vc->one,"default");
			evas_object_show(vc->one);
		}
		if (!vc->three) {
			vc->three = elm_button_add(vc->grid1);
		}
		if (vc->three) {
			evas_object_size_hint_align_set(vc->three, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->three, 1.0, 1.0);			elm_object_text_set(vc->three,_UIB_LOCALE("3"));
			elm_object_style_set(vc->three,"default");
			evas_object_show(vc->three);
		}
		if (!vc->two) {
			vc->two = elm_button_add(vc->grid1);
		}
		if (vc->two) {
			evas_object_size_hint_align_set(vc->two, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->two, 1.0, 1.0);			elm_object_text_set(vc->two,_UIB_LOCALE("2"));
			elm_object_style_set(vc->two,"default");
			evas_object_show(vc->two);
		}
		if (!vc->four) {
			vc->four = elm_button_add(vc->grid1);
		}
		if (vc->four) {
			evas_object_size_hint_align_set(vc->four, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->four, 1.0, 1.0);			elm_object_text_set(vc->four,_UIB_LOCALE("4"));
			elm_object_style_set(vc->four,"default");
			evas_object_show(vc->four);
		}
		if (!vc->five) {
			vc->five = elm_button_add(vc->grid1);
		}
		if (vc->five) {
			evas_object_size_hint_align_set(vc->five, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->five, 1.0, 1.0);			elm_object_text_set(vc->five,_UIB_LOCALE("5"));
			elm_object_style_set(vc->five,"default");
			evas_object_show(vc->five);
		}
		if (!vc->reconfig) {
			vc->reconfig = elm_button_add(vc->grid1);
		}
		if (vc->reconfig) {
			evas_object_size_hint_align_set(vc->reconfig, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->reconfig, 1.0, 1.0);			elm_object_text_set(vc->reconfig,_UIB_LOCALE("RESET SERVICES"));
			elm_object_style_set(vc->reconfig,"default");
			evas_object_hide(vc->reconfig);
		}
		if (!vc->Exit) {
			vc->Exit = elm_button_add(vc->grid1);
		}
		if (vc->Exit) {
			evas_object_size_hint_align_set(vc->Exit, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->Exit, 1.0, 1.0);			elm_object_text_set(vc->Exit,_UIB_LOCALE("Exit"));
			elm_object_style_set(vc->Exit,"bottom");
			evas_object_hide(vc->Exit);
		}
		elm_grid_pack(vc->grid1, vc->bg2, 203, 135, 592, 169);		elm_grid_pack(vc->grid1, vc->Ok, 307, 755, 395, 361);		elm_grid_pack(vc->grid1, vc->password, 206, 147, 587, 156);		elm_grid_pack(vc->grid1, vc->one, 45, 355, 160, 300);		elm_grid_pack(vc->grid1, vc->three, 415, 355, 160, 300);		elm_grid_pack(vc->grid1, vc->two, 230, 355, 160, 300);		elm_grid_pack(vc->grid1, vc->four, 597, 355, 160, 300);		elm_grid_pack(vc->grid1, vc->five, 782, 355, 160, 300);		elm_grid_pack(vc->grid1, vc->reconfig, 127, 267, 742, 364);		elm_grid_pack(vc->grid1, vc->Exit, 143, 748, 714, 364);		evas_object_show(vc->grid1);
	}
}

