/*******************************************************************************
* This file was generated by UI Builder.
* User should hand edit this file.
********************************************************************************/

#include "app_main.h"
#include "uib_views.h"
#include "uib_views_inc.h"
#include "string.h"
#include "app_alarm.h"

typedef struct _uib_view1_control_context {
 /* add your variables here */

} uib_view1_control_context;


char * entpass= "";
int counter=0;

char* concat(const char *s1, const char *s2)
{
    char *result = malloc(strlen(s1) + strlen(s2) + 1); // +1 for the null-terminator
    // in real code you would check for errors in malloc here
    strcpy(result, s1);
    strcat(result, s2);
    return result;
}


void alarm_set(){
    int ret,alarm_id;
	struct tm date;
	ret = alarm_get_current_time(&date);
    app_control_h app_control = NULL;

	date.tm_sec += 4;

    ret = app_control_create(&app_control);
    ret = app_control_set_operation(app_control, APP_CONTROL_OPERATION_DEFAULT);
    ret = app_control_set_app_id(app_control, "org.example.myppgservice");
    //ret=alarm_schedule_once_at_date(app_control, &date, &alarm_id);
	ret = alarm_schedule_at_date(app_control, &date,0, &alarm_id);
}



void view1_Ok_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {

	const char* pass= elm_entry_entry_get(vc->password);

	if(strcmp(pass, "1514")==0){
		entpass="";
		evas_object_hide(vc->password);
		evas_object_hide(vc->Ok);
		evas_object_hide(vc->one);
		evas_object_hide(vc->two);
		evas_object_hide(vc->three);
		evas_object_hide(vc->four);
		evas_object_hide(vc->five);
		evas_object_hide(vc->bg2);

		evas_object_show(vc->Exit);
		evas_object_show(vc->reconfig);

	}
	else{
		elm_object_text_set(vc->password,"Wrong Password");
		entpass="";
		if(counter<3)
			counter++;
		else {
			evas_object_hide(vc->Ok);
			evas_object_hide(vc->one);
			evas_object_hide(vc->two);
			evas_object_hide(vc->three);
			evas_object_hide(vc->four);
			evas_object_hide(vc->five);

			evas_object_show(vc->Exit);
		}

	}
}

void view1_one_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	entpass = concat(entpass, "1");
	elm_object_text_set(vc->password,entpass);
}

void view1_two_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	entpass = concat(entpass, "2");
	elm_object_text_set(vc->password,entpass);
}

void view1_three_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	entpass = concat(entpass, "3");
	elm_object_text_set(vc->password,entpass);
}

void view1_four_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	entpass = concat(entpass, "4");
	elm_object_text_set(vc->password,entpass);
}

void view1_five_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	entpass = concat(entpass, "5");
	elm_object_text_set(vc->password,entpass);
}

void view1_reconfig_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	alarm_cancel_all();
	alarm_set();
	elm_object_disabled_set(vc->reconfig, 1);
	elm_object_text_set(vc->reconfig,"Reset Done");
}

void view1_Exit_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	uib_views_get_instance()->destroy_window_obj();
	ui_app_exit();
}

