
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/
		#include "g_inc_uib.h"
#include "uib_views.h"
#include "uib_views_inc.h"
#include "uib_app_manager.h"


/* event handler declarations */
void mainView_onuib_view_create(uib_mainView_view_context*, Evas_Object*, void*);
void mainView_sendButton_onclicked(uib_mainView_view_context*, Evas_Object*, void*);
void mainView_exitButton_onclicked(uib_mainView_view_context*, Evas_Object*, void*);

uib_view_context* uib_view_mainView_create(Evas_Object* parent, void* create_callback_param) {
	uib_mainView_view_context* vc = calloc(1, sizeof(uib_mainView_view_context));
	vc->parent = parent;
	vc->view_name = "mainView";
	vc->indicator_state = ELM_WIN_INDICATOR_HIDE;
	vc->is_user_view = false;
	uib_app_manager_get_instance()->add_view_context((uib_view_context*)vc);
	if (!vc->mainGrid) {
		vc->mainGrid= elm_grid_add(parent);
		vc->root_container = vc->mainGrid;
	}
	uib_views_get_instance()->set_targeted_view((uib_view_context*)vc);

	//bind event handler
	evas_object_smart_callback_add(vc->root_container, "uib,view,create", (Evas_Smart_Cb)mainView_onuib_view_create, vc);
	evas_object_smart_callback_add(vc->sendButton, "clicked", (Evas_Smart_Cb)mainView_sendButton_onclicked, vc);
	evas_object_smart_callback_add(vc->exitButton, "clicked", (Evas_Smart_Cb)mainView_exitButton_onclicked, vc);


	evas_object_data_set(vc->root_container, KEY_VIEW_CONTEXT, vc);
	uib_views_create_callback(vc, evas_object_evas_get(vc->root_container), vc->root_container, create_callback_param);
	evas_object_event_callback_add(vc->root_container, EVAS_CALLBACK_DEL, (Evas_Object_Event_Cb)uib_views_destroy_callback, vc);

	return (uib_view_context*)vc;
}
void uib_mainView_config_CIRCLE_360x360_portrait() {
	uib_app_manager_st* uib_app_manager = uib_app_manager_get_instance();
	uib_mainView_view_context* vc = (uib_mainView_view_context*)uib_app_manager->find_view_context("mainView");
	if(!vc) {
		return;
	}
	if(vc->mainGrid) {
		elm_grid_clear(vc->mainGrid, EINA_FALSE);
		evas_object_size_hint_align_set(vc->mainGrid, -1.0, -1.0);		evas_object_size_hint_weight_set(vc->mainGrid, 1.0, 1.0);		elm_grid_size_set(vc->mainGrid, 1000, 1000);
		if (!vc->sendButton) {
			vc->sendButton = elm_button_add(vc->mainGrid);
		}
		if (vc->sendButton) {
			evas_object_size_hint_align_set(vc->sendButton, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->sendButton, 1.0, 1.0);			elm_object_text_set(vc->sendButton,_UIB_LOCALE("SEND"));
			elm_object_style_set(vc->sendButton,"bottom");
			evas_object_show(vc->sendButton);
		}
		if (!vc->exitButton) {
			vc->exitButton = elm_button_add(vc->mainGrid);
		}
		if (vc->exitButton) {
			evas_object_size_hint_align_set(vc->exitButton, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->exitButton, 1.0, 1.0);			elm_object_text_set(vc->exitButton,_UIB_LOCALE("EXIT"));
			elm_object_style_set(vc->exitButton,"bottom");
			evas_object_show(vc->exitButton);
		}
		if (!vc->msgBox) {
			vc->msgBox = elm_box_add(vc->mainGrid);
		}
		if(vc->msgBox) {
			elm_win_alpha_set(vc->msgBox, EINA_FALSE);
			elm_box_homogeneous_set(vc->msgBox, EINA_FALSE);
			elm_box_horizontal_set(vc->msgBox, EINA_FALSE);
			elm_box_padding_set(vc->msgBox,0,0);
			evas_object_size_hint_align_set(vc->msgBox, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->msgBox, 1.0, 1.0);
			if (!vc->msgLabel) {
				vc->msgLabel = elm_label_add(vc->msgBox);
			}
			if(vc->msgLabel) {
				evas_object_size_hint_align_set(vc->msgLabel, 0.5, 0.5);				evas_object_size_hint_weight_set(vc->msgLabel, 1.0, 1.0);				elm_object_text_set(vc->msgLabel,_UIB_LOCALE("Press Send Button"));
				elm_label_line_wrap_set(vc->msgLabel, (Elm_Wrap_Type)ELM_WRAP_NONE);
				elm_label_wrap_width_set(vc->msgLabel,0);
				elm_label_ellipsis_set(vc->msgLabel, EINA_FALSE);
				evas_object_show(vc->msgLabel);
			}
			elm_box_pack_end(vc->msgBox, vc->msgLabel);
			evas_object_show(vc->msgBox);
		}
		elm_grid_pack(vc->mainGrid, vc->sendButton, 100, -3, 800, 361);		elm_grid_pack(vc->mainGrid, vc->exitButton, 98, 710, 800, 361);		elm_grid_pack(vc->mainGrid, vc->msgBox, 0, 362, 1000, 338);		evas_object_show(vc->mainGrid);
	}
}

